# Generated by Django 3.0.6 on 2020-05-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_code', models.CharField(max_length=100, verbose_name='User name')),
                ('fullname', models.CharField(max_length=100, verbose_name='User name')),
                ('username', models.CharField(max_length=100, verbose_name='User name')),
                ('email', models.CharField(max_length=100, verbose_name='User email')),
                ('password', models.CharField(max_length=200, verbose_name='User Password')),
                ('confirm_password', models.CharField(max_length=100, verbose_name='User email')),
            ],
        ),
    ]
